### PR TITLE
Change BackgroundColors page Design and fix issue #60

### LINKED ISSUE #60: Unwanted movement in background color select page
## 📌 Describe Issue
In background color select page, unwanted movement is occured when user Hover color select button. 

### 🐠 Checklists

- [ ]
- [ ]

### 🚴 Possible(or Suggest) solutions
change css selector 'border' to 'outline'

### 🍳 Environments

- Device:
- OS:
- Browser:
- Version:

### 📷 Screenshots
before

### PR DESCRIPTION
**Pull request by userJu**
## 📄 What I've done
- change BackgroundColors.tsx Style
- close #60 

### ⛱️ Major Changes
- Change border into outline
- Change Typography fontWeight into bold

### 🙋 Review Points
- How about this design? 
-

### 🛰 GIF
before
before

after
after

### CODE REVIEW

**Review by msdio — APPROVED** [review]
Good point 🙂
I've noticed this issue, but never thought about fixing it. Thanks about catching details 🤗

File: src/pages/background-colors/BackgroundColors.tsx [hunk 1]
```diff
@@ -14,11 +14,27 @@ const CustomContainer = styled.div`
...
   '&:hover': {
-    border: `5px solid ${theme.palette.success.main}`,
+    outline: `5px solid ${theme.palette.success.main}`,
+    h1: {
+      opacity: 1,
+    },
   },
 }));
 
+const Color = styled.h1<{ color: string }>`
```
Comment (msdio) [inline src/pages/background-colors/BackgroundColors.tsx:26]: `color` is seem to be have only 1 value, but can I get your opinion about making it into variable?

Comment (userJu) [reply src/pages/background-colors/BackgroundColors.tsx:26]: I thought that color object just have one value, then I write it like that
but be not convinced
